# SPDX-License-Identifier: BSD-3-Clause
# mixer kernel test (NCO + cmad frequency shift) -- see
# ../../common/kernel.mk for the shared build/test/clean rules.

KERNEL = mixer
SRCS   = test_mixer.c kernel/mixer.c

include ../../common/kernel.mk
