// SPDX-License-Identifier: BSD-3-Clause
// mixer kernel test harness -- Python-oracle driven, mirroring
// la931x_vspa_common/vspa-lib/mixer/tests/test_mixer.c's buffer layout,
// but calling our own C+intrinsics kernel (kernel/mixer.c) instead of the
// reference mixer_asm.sx, and simplified to one line (checking the NCO +
// cmad mixing itself, not throughput).
//
// mixer_vspa(py, px, PhaseIn, FreqIn, L) should perform
//   y[k] = x[k] * exp(+2*pi*j*(FreqIn/2^32)*(PhaseIn + k))
// on L lines of AU_COUNT*2 complex 16-bit half-fixed (sign-magnitude)
// samples, returning the updated phase for a following call.
//
// Reference is generated by the vendored r_nco/r_mixer oracle
// (../python/model.py).

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <vspa/intrinsics.h>
#include "test_utils.h"

typedef __fx16 fixed16_t;
typedef struct { fixed16_t real; fixed16_t imag; } cfixed16_t;

extern unsigned int mixer_vspa(cfixed16_t *mix_out, cfixed16_t *mix_in,
                                uint32_t phase_in, int32_t freq_in, uint32_t L);

// One line: AU_COUNT*2 complex samples.
#define LINES   1
#define N_CPLX  (LINES * (__AU_COUNT__ * 2))
#define N_HW    (2 * N_CPLX)

// Mixer parameters -- gen_vectors.py uses the matching values.
#define PHASE_IN 0x12345678u
#define FREQ_IN  0x00123456

// Inputs/reference from gen_vectors.py: one halfword per line, interleaved
// real/imag, sign-magnitude SM16 (== half_fixed) encoding.
static const int16_t INPUT_DATA[N_HW] = {
#include "vectors/input.hex"
};
static const int16_t REF_DATA[N_HW] = {
#include "vectors/ref.hex"
};

_VSPA_VECTOR_ALIGN static int16_t MIXER_INP_BUFF[N_HW];
_VSPA_VECTOR_ALIGN static int16_t MIXER_OUT_BUFF[N_HW];

int main(void)
{
    int i;

    for (i = 0; i < N_HW; i++)
        MIXER_INP_BUFF[i] = INPUT_DATA[i];

    KCYC_INIT();
    KCYC_START();
    (void)mixer_vspa((cfixed16_t *)MIXER_OUT_BUFF,
                      (cfixed16_t *)MIXER_INP_BUFF,
                      PHASE_IN, FREQ_IN, LINES);
    KCYC_STOP_PRINT();

    return vspa_array_cmp((const unsigned *)MIXER_OUT_BUFF,
                          (const unsigned *)REF_DATA,
                          N_CPLX);
}
